name: My tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '11'

    - name: Run mvn
      run: mvn --version

    - name: Set up project information
      run: |
        export REF=${{ github.event.client_payload.event.ref }}
        echo "BRANCH_NAME=$(echo "${REF#refs/heads/}")" >> $GITHUB_ENV

    - name: Run mvn with env set
      env:
        FOO: bar
      run: mvn --version
