name: My tests
on: [push]

jobs:
  test:
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '11'

    - name: echo $PATH
      run: echo $PATH

    - name: echo $PATH with env set
      env:
        FOO: bar
      run: echo $PATH
